<?xml version="1.0" ?>
<!DOCTYPE comuni [
  <!ELEMENT comuni (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (ID?,name?,slug?,lat?,lng?,codice_provincia_istat?,codice_comune_istat?,codice_alfanumerico_istat?,capoluogo_provincia?,capoluogo_regione?)+>
  <!ELEMENT ID (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT slug (#PCDATA)>
  <!ELEMENT lat (#PCDATA)>
  <!ELEMENT lng (#PCDATA)>
  <!ELEMENT codice_provincia_istat (#PCDATA)>
  <!ELEMENT codice_comune_istat (#PCDATA)>
  <!ELEMENT codice_alfanumerico_istat (#PCDATA)>
  <!ELEMENT capoluogo_provincia (#PCDATA)>
  <!ELEMENT capoluogo_regione (#PCDATA)>
]>
<comuni>
  <DATA_RECORD>
    <ID>1</ID>
    <name>Agli√®</name>
    <slug>aglie</slug>
    <lat>45.3681</lat>
    <lng>7.7681</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>001</codice_comune_istat>
    <codice_alfanumerico_istat>001001</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>2</ID>
    <name>Airasca</name>
    <slug>airasca</slug>
    <lat>44.9181</lat>
    <lng>7.4855</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>002</codice_comune_istat>
    <codice_alfanumerico_istat>001002</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>3</ID>
    <name>Ala di Stura</name>
    <slug>ala-di-stura</slug>
    <lat>45.3154</lat>
    <lng>7.3026</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>003</codice_comune_istat>
    <codice_alfanumerico_istat>001003</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>4</ID>
    <name>Albiano d'Ivrea</name>
    <slug>albiano-divrea</slug>
    <lat>45.4339</lat>
    <lng>7.9517</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>004</codice_comune_istat>
    <codice_alfanumerico_istat>001004</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>5</ID>
    <name>Alice Superiore</name>
    <slug>alice-superiore</slug>
    <lat>45.4599</lat>
    <lng>7.7774</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>005</codice_comune_istat>
    <codice_alfanumerico_istat>001005</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>6</ID>
    <name>Almese</name>
    <slug>almese</slug>
    <lat>45.1169</lat>
    <lng>7.3954</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>006</codice_comune_istat>
    <codice_alfanumerico_istat>001006</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>7</ID>
    <name>Alpette</name>
    <slug>alpette</slug>
    <lat>45.4106</lat>
    <lng>7.5808</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>007</codice_comune_istat>
    <codice_alfanumerico_istat>001007</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>8</ID>
    <name>Alpignano</name>
    <slug>alpignano</slug>
    <lat>45.0943</lat>
    <lng>7.5244</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>008</codice_comune_istat>
    <codice_alfanumerico_istat>001008</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>9</ID>
    <name>Andezeno</name>
    <slug>andezeno</slug>
    <lat>45.0373</lat>
    <lng>7.8731</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>009</codice_comune_istat>
    <codice_alfanumerico_istat>001009</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>10</ID>
    <name>Andrate</name>
    <slug>andrate</slug>
    <lat>45.5285</lat>
    <lng>7.8814</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>010</codice_comune_istat>
    <codice_alfanumerico_istat>001010</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>11</ID>
    <name>Angrogna</name>
    <slug>angrogna</slug>
    <lat>44.8438</lat>
    <lng>7.2246</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>011</codice_comune_istat>
    <codice_alfanumerico_istat>001011</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>12</ID>
    <name>Arignano</name>
    <slug>arignano</slug>
    <lat>45.0438</lat>
    <lng>7.9011</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>012</codice_comune_istat>
    <codice_alfanumerico_istat>001012</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>13</ID>
    <name>Avigliana</name>
    <slug>avigliana</slug>
    <lat>45.0793</lat>
    <lng>7.3967</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>013</codice_comune_istat>
    <codice_alfanumerico_istat>001013</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>14</ID>
    <name>Azeglio</name>
    <slug>azeglio</slug>
    <lat>45.4246</lat>
    <lng>7.995</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>014</codice_comune_istat>
    <codice_alfanumerico_istat>001014</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>15</ID>
    <name>Bairo</name>
    <slug>bairo</slug>
    <lat>45.387</lat>
    <lng>7.7564</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>015</codice_comune_istat>
    <codice_alfanumerico_istat>001015</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>16</ID>
    <name>Balangero</name>
    <slug>balangero</slug>
    <lat>45.2714</lat>
    <lng>7.5186</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>016</codice_comune_istat>
    <codice_alfanumerico_istat>001016</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>17</ID>
    <name>Baldissero Canavese</name>
    <slug>baldissero-canavese</slug>
    <lat>45.4112</lat>
    <lng>7.7453</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>017</codice_comune_istat>
    <codice_alfanumerico_istat>001017</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>18</ID>
    <name>Baldissero Torinese</name>
    <slug>baldissero-torinese</slug>
    <lat>45.0685</lat>
    <lng>7.817</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>018</codice_comune_istat>
    <codice_alfanumerico_istat>001018</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>19</ID>
    <name>Balme</name>
    <slug>balme</slug>
    <lat>45.3022</lat>
    <lng>7.2181</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>019</codice_comune_istat>
    <codice_alfanumerico_istat>001019</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>20</ID>
    <name>Banchette</name>
    <slug>banchette</slug>
    <lat>45.4545</lat>
    <lng>7.8575</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>020</codice_comune_istat>
    <codice_alfanumerico_istat>001020</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>21</ID>
    <name>Barbania</name>
    <slug>barbania</slug>
    <lat>45.2924</lat>
    <lng>7.6314</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>021</codice_comune_istat>
    <codice_alfanumerico_istat>001021</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>22</ID>
    <name>Bardonecchia</name>
    <slug>bardonecchia</slug>
    <lat>45.0788</lat>
    <lng>6.7043</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>022</codice_comune_istat>
    <codice_alfanumerico_istat>001022</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>23</ID>
    <name>Barone Canavese</name>
    <slug>barone-canavese</slug>
    <lat>45.3267</lat>
    <lng>7.8745</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>023</codice_comune_istat>
    <codice_alfanumerico_istat>001023</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>24</ID>
    <name>Beinasco</name>
    <slug>beinasco</slug>
    <lat>45.0228</lat>
    <lng>7.5878</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>024</codice_comune_istat>
    <codice_alfanumerico_istat>001024</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>25</ID>
    <name>Bibiana</name>
    <slug>bibiana</slug>
    <lat>44.8</lat>
    <lng>7.2894</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>025</codice_comune_istat>
    <codice_alfanumerico_istat>001025</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>26</ID>
    <name>Bobbio Pellice</name>
    <slug>bobbio-pellice</slug>
    <lat>44.8078</lat>
    <lng>7.1178</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>026</codice_comune_istat>
    <codice_alfanumerico_istat>001026</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>27</ID>
    <name>Bollengo</name>
    <slug>bollengo</slug>
    <lat>45.4703</lat>
    <lng>7.9466</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>027</codice_comune_istat>
    <codice_alfanumerico_istat>001027</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>28</ID>
    <name>Borgaro Torinese</name>
    <slug>borgaro-torinese</slug>
    <lat>45.1517</lat>
    <lng>7.6578</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>028</codice_comune_istat>
    <codice_alfanumerico_istat>001028</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>29</ID>
    <name>Borgiallo</name>
    <slug>borgiallo</slug>
    <lat>45.4181</lat>
    <lng>7.6697</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>029</codice_comune_istat>
    <codice_alfanumerico_istat>001029</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>30</ID>
    <name>Borgofranco d'Ivrea</name>
    <slug>borgofranco-divrea</slug>
    <lat>45.5139</lat>
    <lng>7.8592</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>030</codice_comune_istat>
    <codice_alfanumerico_istat>001030</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>31</ID>
    <name>Borgomasino</name>
    <slug>borgomasino</slug>
    <lat>45.3642</lat>
    <lng>7.9888</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>031</codice_comune_istat>
    <codice_alfanumerico_istat>001031</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>32</ID>
    <name>Borgone Susa</name>
    <slug>borgone-susa</slug>
    <lat>45.1212</lat>
    <lng>7.2398</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>032</codice_comune_istat>
    <codice_alfanumerico_istat>001032</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>33</ID>
    <name>Bosconero</name>
    <slug>bosconero</slug>
    <lat>45.268</lat>
    <lng>7.7641</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>033</codice_comune_istat>
    <codice_alfanumerico_istat>001033</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>34</ID>
    <name>Brandizzo</name>
    <slug>brandizzo</slug>
    <lat>45.1783</lat>
    <lng>7.8389</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>034</codice_comune_istat>
    <codice_alfanumerico_istat>001034</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>35</ID>
    <name>Bricherasio</name>
    <slug>bricherasio</slug>
    <lat>44.8245</lat>
    <lng>7.3066</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>035</codice_comune_istat>
    <codice_alfanumerico_istat>001035</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>36</ID>
    <name>Brosso</name>
    <slug>brosso</slug>
    <lat>45.494</lat>
    <lng>7.8039</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>036</codice_comune_istat>
    <codice_alfanumerico_istat>001036</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>37</ID>
    <name>Brozolo</name>
    <slug>brozolo</slug>
    <lat>45.1177</lat>
    <lng>8.0725</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>037</codice_comune_istat>
    <codice_alfanumerico_istat>001037</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>38</ID>
    <name>Bruino</name>
    <slug>bruino</slug>
    <lat>45.0212</lat>
    <lng>7.4646</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>038</codice_comune_istat>
    <codice_alfanumerico_istat>001038</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>39</ID>
    <name>Brusasco</name>
    <slug>brusasco</slug>
    <lat>45.1558</lat>
    <lng>8.0595</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>039</codice_comune_istat>
    <codice_alfanumerico_istat>001039</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>40</ID>
    <name>Bruzolo</name>
    <slug>bruzolo</slug>
    <lat>45.1434</lat>
    <lng>7.1938</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>040</codice_comune_istat>
    <codice_alfanumerico_istat>001040</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>41</ID>
    <name>Buriasco</name>
    <slug>buriasco</slug>
    <lat>44.8747</lat>
    <lng>7.4114</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>041</codice_comune_istat>
    <codice_alfanumerico_istat>001041</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>42</ID>
    <name>Burolo</name>
    <slug>burolo</slug>
    <lat>45.4822</lat>
    <lng>7.935</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>042</codice_comune_istat>
    <codice_alfanumerico_istat>001042</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>43</ID>
    <name>Busano</name>
    <slug>busano</slug>
    <lat>45.3331</lat>
    <lng>7.6571</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>043</codice_comune_istat>
    <codice_alfanumerico_istat>001043</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>44</ID>
    <name>Bussoleno</name>
    <slug>bussoleno</slug>
    <lat>45.1414</lat>
    <lng>7.1475</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>044</codice_comune_istat>
    <codice_alfanumerico_istat>001044</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>45</ID>
    <name>Buttigliera Alta</name>
    <slug>buttigliera-alta</slug>
    <lat>45.071</lat>
    <lng>7.4295</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>045</codice_comune_istat>
    <codice_alfanumerico_istat>001045</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>46</ID>
    <name>Cafasse</name>
    <slug>cafasse</slug>
    <lat>45.2461</lat>
    <lng>7.5184</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>046</codice_comune_istat>
    <codice_alfanumerico_istat>001046</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>47</ID>
    <name>Caluso</name>
    <slug>caluso</slug>
    <lat>45.3059</lat>
    <lng>7.8969</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>047</codice_comune_istat>
    <codice_alfanumerico_istat>001047</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>48</ID>
    <name>Cambiano</name>
    <slug>cambiano</slug>
    <lat>44.9694</lat>
    <lng>7.7731</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>048</codice_comune_istat>
    <codice_alfanumerico_istat>001048</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>49</ID>
    <name>Campiglione-Fenile</name>
    <slug>campiglione-fenile</slug>
    <lat>44.8025</lat>
    <lng>7.3235</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>049</codice_comune_istat>
    <codice_alfanumerico_istat>001049</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>50</ID>
    <name>Candia Canavese</name>
    <slug>candia-canavese</slug>
    <lat>45.3288</lat>
    <lng>7.8863</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>050</codice_comune_istat>
    <codice_alfanumerico_istat>001050</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>51</ID>
    <name>Candiolo</name>
    <slug>candiolo</slug>
    <lat>44.9603</lat>
    <lng>7.6028</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>051</codice_comune_istat>
    <codice_alfanumerico_istat>001051</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>52</ID>
    <name>Canischio</name>
    <slug>canischio</slug>
    <lat>45.3745</lat>
    <lng>7.5958</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>052</codice_comune_istat>
    <codice_alfanumerico_istat>001052</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>53</ID>
    <name>Cantalupa</name>
    <slug>cantalupa</slug>
    <lat>44.947</lat>
    <lng>7.3314</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>053</codice_comune_istat>
    <codice_alfanumerico_istat>001053</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>54</ID>
    <name>Cantoira</name>
    <slug>cantoira</slug>
    <lat>45.3395</lat>
    <lng>7.387</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>054</codice_comune_istat>
    <codice_alfanumerico_istat>001054</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>55</ID>
    <name>Caprie</name>
    <slug>caprie</slug>
    <lat>45.1198</lat>
    <lng>7.3331</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>055</codice_comune_istat>
    <codice_alfanumerico_istat>001055</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>56</ID>
    <name>Caravino</name>
    <slug>caravino</slug>
    <lat>45.3992</lat>
    <lng>7.9614</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>056</codice_comune_istat>
    <codice_alfanumerico_istat>001056</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>57</ID>
    <name>Carema</name>
    <slug>carema</slug>
    <lat>45.5845</lat>
    <lng>7.8119</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>057</codice_comune_istat>
    <codice_alfanumerico_istat>001057</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>58</ID>
    <name>Carignano</name>
    <slug>carignano</slug>
    <lat>44.908</lat>
    <lng>7.6744</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>058</codice_comune_istat>
    <codice_alfanumerico_istat>001058</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>59</ID>
    <name>Carmagnola</name>
    <slug>carmagnola</slug>
    <lat>44.8455</lat>
    <lng>7.7192</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>059</codice_comune_istat>
    <codice_alfanumerico_istat>001059</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>60</ID>
    <name>Casalborgone</name>
    <slug>casalborgone</slug>
    <lat>45.1312</lat>
    <lng>7.9414</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>060</codice_comune_istat>
    <codice_alfanumerico_istat>001060</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>61</ID>
    <name>Cascinette d'Ivrea</name>
    <slug>cascinette-divrea</slug>
    <lat>45.4813</lat>
    <lng>7.9067</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>061</codice_comune_istat>
    <codice_alfanumerico_istat>001061</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>62</ID>
    <name>Caselette</name>
    <slug>caselette</slug>
    <lat>45.1058</lat>
    <lng>7.4821</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>062</codice_comune_istat>
    <codice_alfanumerico_istat>001062</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>63</ID>
    <name>Caselle Torinese</name>
    <slug>caselle-torinese</slug>
    <lat>45.1774</lat>
    <lng>7.6475</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>063</codice_comune_istat>
    <codice_alfanumerico_istat>001063</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>64</ID>
    <name>Castagneto Po</name>
    <slug>castagneto-po</slug>
    <lat>45.1603</lat>
    <lng>7.8906</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>064</codice_comune_istat>
    <codice_alfanumerico_istat>001064</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>65</ID>
    <name>Castagnole Piemonte</name>
    <slug>castagnole-piemonte</slug>
    <lat>44.8992</lat>
    <lng>7.5674</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>065</codice_comune_istat>
    <codice_alfanumerico_istat>001065</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>66</ID>
    <name>Castellamonte</name>
    <slug>castellamonte</slug>
    <lat>45.383</lat>
    <lng>7.7133</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>066</codice_comune_istat>
    <codice_alfanumerico_istat>001066</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>67</ID>
    <name>Castelnuovo Nigra</name>
    <slug>castelnuovo-nigra</slug>
    <lat>45.4392</lat>
    <lng>7.6958</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>067</codice_comune_istat>
    <codice_alfanumerico_istat>001067</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>68</ID>
    <name>Castiglione Torinese</name>
    <slug>castiglione-torinese</slug>
    <lat>45.1202</lat>
    <lng>7.8155</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>068</codice_comune_istat>
    <codice_alfanumerico_istat>001068</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>69</ID>
    <name>Cavagnolo</name>
    <slug>cavagnolo</slug>
    <lat>45.1529</lat>
    <lng>8.0501</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>069</codice_comune_istat>
    <codice_alfanumerico_istat>001069</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>70</ID>
    <name>Cavour</name>
    <slug>cavour</slug>
    <lat>44.7857</lat>
    <lng>7.375</lng>
    <codice_provincia_istat>001</codice_provincia_istat>
    <codice_comune_istat>070</codice_comune_istat>
    <codice_alfanumerico_istat>001070</codice_alfanumerico_istat>
    <capoluogo_provincia>0</capoluogo_provincia>
    <capoluogo_regione>0</capoluogo_regione>
  </DATA_RECORD>
  <DATA_RECORD>
    <ID>71</ID>
    <name>Cercenasco</name>
    <slug>cercenasco</slug>
    <lat>44.8606</lat>